### ISSUE TITLE
CC-28: Design Leaderboard Pages

### ISSUE THREAD

**Issue by RyanDhingra** [RyanDhingra/Code-Clash#39]
Create a leaderboard page in figma that displays player rankings based on different game modes. The leaderboard should provide an intuitive and user-friendly interface for players to view their rankings, and it should support multiple game modes.

**Comment by iammathavan** [comment]
https://www.figma.com/file/Uchmf9bol6AnoRdmS8annu/CC---28---Design-Leaderboard?type=design&node-id=1%3A2&mode=design&t=FcLsBIpe8UEq30zD-1
