### ISSUE TITLE
CC-30.1: Gamemode How-To Scripts

### ISSUE THREAD

**Issue by RyanDhingra** [RyanDhingra/Code-Clash#41]
Write a short script that provides concise and informative descriptions for each game mode. The script should be engaging and capture the essence of each game mode, guiding players on how to play and what to expect. The goal is to enhance the player's understanding of the various game modes, encouraging them to explore and enjoy the diverse gaming experiences offered.

**Comment by Methilan** [comment]
https://docs.google.com/document/d/1sk997-JO6oMTcKOADYyjIqmxDD0DpUb8-oHApwADXhI/edit?usp=sharing
