### ISSUE TITLE
CC-31: Endgame Screen

### ISSUE THREAD

**Issue by RyanDhingra** [RyanDhingra/Code-Clash#43]
Develop the visual design for the Game Over functionality and the Match Results screen using Figma. The goal is to create an aesthetically pleasing and informative screen that provides players with relevant information about their performance, highlights key achievements, and offers a smooth transition from gameplay to the end game experience.

**Comment by Methilan** [comment]
https://www.figma.com/file/ZNqBq5e6ucCuAHHgU3Q2JC/CC-31%3A-Endgame-Screen?type=design&node-id=0%3A1&mode=design&t=jdLFsfz0Qp18AJhh-1
